### ISSUE TITLE
Upgrade to React 0.11.1

### ISSUE THREAD

**Issue by amireh** [jasmine-addons/jasmine_react#1]
It seems like `React.addons.TestUtils` no longer exists, which is a rather API-breaking change for this library.

**Comment by CezaryDanielNowak** [comment]
Hej, I've checked: TestUtils exists in 0.12.2.

**Comment by amireh** [comment]
Yeah, I believe I was checking the version that didn't include the add-ons when I opened this. Thanks for the heads up though! :)

Closing this as 0.11 has been supported since the [v1.1.0](https://github.com/jasmine-addons/jasmine_react/commit/5d0db50a58aba6c74fd84367081de9e6002ba78a#diff-04c6e90faac2675aa89e2176d2eec7d8) commit.
